<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-08-23T11:17:44+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Kuala_Lumpur',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
