<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-08-24T23:23:16+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.5',
    'version_db_installed' => '20201116182100',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1629688662,
        'latest_version' => '8.5.5',
        'do_page_reindex_check' => false,
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'permissions' => [
        'model' => 'advanced',
    ],
];
