<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-08-24T23:36:33+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'My Store Yaw',
            'editor' => [
                'concrete' => [
                    'enable_filemanager' => true,
                    'enable_sitemap' => true,
                ],
                'ckeditor4' => [
                    'plugins' => [
                        'selected' => [
                            'concrete5filemanager',
                            'concrete5inline',
                            'concrete5uploadimage',
                            'dialogadvtab',
                            'divarea',
                            'floatingspace',
                            'normalizeonchange',
                            'resize',
                            'toolbar',
                            'wysiwygarea',
                            'a11yhelp',
                            'autogrow',
                            'basicstyles',
                            'colordialog',
                            'concrete5link',
                            'concrete5styles',
                            'contextmenu',
                            'elementspath',
                            'enterkey',
                            'entities',
                            'font',
                            'format',
                            'htmlwriter',
                            'image',
                            'indentblock',
                            'indentlist',
                            'justify',
                            'list',
                            'liststyle',
                            'magicline',
                            'removeformat',
                            'showblocks',
                            'showborders',
                            'sourcedialog',
                            'sourcearea',
                            'stylescombo',
                            'tab',
                            'table',
                            'tableresize',
                            'tableselection',
                            'tabletools',
                            'undo',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
